# Generated by Django 3.2 on 2023-05-20 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_tipo_doc', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('cod_localidad', models.IntegerField(primary_key=True, serialize=False)),
                ('localidad', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('cod_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Sexos',
            fields=[
                ('id_tipo_sexo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.TextField(max_length=150)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'db_table': 'Sexos',
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('cod_provincia', models.IntegerField(primary_key=True, serialize=False)),
                ('provincia', models.TextField(max_length=150)),
                ('cod_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankarg_ispc.paises')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=120)),
                ('apellido', models.TextField(max_length=120)),
                ('nro_doc', models.CharField(max_length=20)),
                ('nro_calle', models.IntegerField()),
                ('calle', models.TextField(max_length=150)),
                ('fecha_nac', models.DateTimeField()),
                ('cod_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankarg_ispc.localidades')),
                ('id_tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankarg_ispc.documentos')),
                ('id_tipo_sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankarg_ispc.sexos')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Persona',
            },
        ),
        migrations.AddField(
            model_name='localidades',
            name='cod_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankarg_ispc.provincias'),
        ),
    ]
