# Generated by Django 3.2 on 2023-05-20 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankarg_ispc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='bankarg_ispc.persona')),
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nro_afiliado', models.IntegerField()),
            ],
            bases=('bankarg_ispc.persona',),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='id_tipo_doc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localidades',
            name='cod_localidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paises',
            name='cod_pais',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provincias',
            name='cod_provincia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sexos',
            name='id_tipo_sexo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
