# Generated by Django 3.2 on 2023-06-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankarg_ispc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(),
        ),
    ]
