# Generated by Django 3.2 on 2023-06-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankarg_ispc', '0002_alter_persona_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='fecha_pago',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
